# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [1]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [2]:
# Solución (:
arrachera = np.zeros([3,4])
print(arrachera)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [5]:
# Solucion :)
arraydado = np.arange(1,6)
print(sum(arraydado))


15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [6]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)
print("Minimo:", min(array))
print("Maximo:", max(array))

Minimo: 10
Maximo: 50


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [7]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])

# Solución:)
print("Minimo:", min(array))
print("Maximo:", max(array))

Minimo: 10
Maximo: 50


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [ ]:
# Solución:)
alea = np.random.randint(0,2,5)
print(alea)

[1 1 1 1 1]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [24]:
#Solucion:)
array1 = np.arange(5,26,5)
print(array1)
print("Promedio: ", array1.mean)

[ 5 10 15 20 25]
Promedio:  <built-in method mean of numpy.ndarray object at 0x0000020D3CDDB7B0>


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [5]:
#Solucion:)
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("Arreglo 1: ",arr1)
print("Arreglo 2: ",arr2)
print("Arreglo concatenado: ", np.concatenate((arr1,arr2),axis=0))

Arreglo 1:  [1 2 3]
Arreglo 2:  [4 5 6]
Arreglo concatenado:  [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [7]:
#Solución:)
arre = np.array([1,2,3,4,5,6])
print("Arreglo inicial:\n",arre)
arren = arre.reshape(2,3)
print("Arreglo nuevo:\n",arren)

Arreglo inicial:
 [1 2 3 4 5 6]
Arreglo nuevo:
 [[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [8]:
#Solución:)
A = np.array([1,2,3])
B = np.array([4,5,6])
C = np.dot(A,B)
print(C)

32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [9]:
#Solución:)
arre = np.array([1,2,3,4,5,6,7,8,9,10])
print(arre)
arren = arre.reshape(2,5)
print(arren)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [ ]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])
encontrado = np.partition(arr, 2)[2]
print("Third least element:", encontrado)

Third least element: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [10]:
# Solucion del ROIROIROIROIORIORI
inv = np.array([1000,1500,2000])
ret = np.array([1200,1650,1800])

calc = (ret - inv)/(inv * 100)
print(calc)

[ 0.002  0.001 -0.001]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [11]:
dataset = np.array([250,320,150,500,210])
minD = np.min(dataset)
maxD = np.max(dataset)
normalizar = (dataset - minD)/(maxD - minD)
print(normalizar)

[0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [14]:
ventas = np.array([1200,0,750,2400,0,1800])
prom = np.mean(ventas[ventas != 0])
print("Promedio de dias con ventas: ",prom)

ventas[ventas == 0 ] = prom
print(ventas)

Promedio de dias con ventas:  1537.5
[1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [ ]:
pacientes = np.array([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])
print("Pacientes: ",pacientes)
print("Media: ",np.mean(pacientes))
print("Desvacion estandar: ",np.std(pacientes))
print("Pacientes malitos: ", pacientes[(pacientes < 90) | (pacientes > 140)])

Pacientes:  [120 135 140 118 150 130 160 125 142 128]
Meia:  134.8
Desvacion estandar:  12.69488085804668
Pacientes malitos:  [150 160 142]


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [29]:
pibs = np.array([500,320,700,450])
pobs = np.array([10,8,12,9])
pibpc = pibs/pobs
print("Pib per capita o7",pibpc)
print("Pais con mas pibpc:",np.max(pibpc),"millones")


Pib per capita o7 [50.         40.         58.33333333 50.        ]
Pais con mas pibpc: 58.333333333333336 millones


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [80]:
valores = np.random.randint(1,101,100)
print(valores)

pociones = valores[valores <= 50]
armas = valores[valores <= 15]
artefactos = valores[valores <= 5]

print("Artefactos: ", np.size(artefactos))

[ 69  56  46  97  61  91  71  76  87  74  46  62  33  60  74  52  38  84
  59   4  35  29  47  86  15  50  13  61  74   9  85  69  47  83  17  10
  85  33  90  97  40  30  95   1  25  47  59  82  40  30  57  46 100  41
  20  35  46  40  61  73  40  15  78  69   4  28  72   8  77   9  91   7
  47  44   3  46  19  35  30  79  19  89  48  88  84  90  90  49  89  82
  49  13  72  55  67  71  95  24  81  58]
Artefactos:  4
